version: '3'
services:

  elasticsearch:
    image: elasticsearch:7.14.1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.14.1
    ports: ['5601:5601']
    links: ['elasticsearch']
    depends_on: ['elasticsearch']