# Generated by Django 3.2.8 on 2021-10-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20211011_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hashsum', models.CharField(max_length=50)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='DataPoint',
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
