FROM jupyter/minimal-notebook

RUN jupyter labextension install jupyterlab-code-snippets

CP snippets.json /home/jovyan/.jupyter/lab/user-settings/jupyterlab-code-snippets/snippets.jupyterlab-settings \


CP standard.jupyter.dir to and define jupyter-lab --notebook-dir="test"
CP http://127.0.0.1:8888/lab?token=140fbdcc26af49ecd39b3b348e1986d29dd79d316e241e95